import Banner from "@/components/Banner";
import PopulerMovies from "@/components/PopulerMovies";
import Promos from "@/components/Promos";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto min-h-screen px-2 mb-6 bg-main">
        <Banner />
        <PopulerMovies />
        <Promos/>
      </main>
    </>
  );
}
